version: '3.8'

services:
  app:
    container_name: simple_stock_web
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - simple_stock_net
    depends_on:
      - db

  db:
    container_name: simple_stock_db
    build: ./BD/
    environment:
      MYSQL_DATABASE: simple_stock
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  zap: # https://www.zaproxy.org/docs/docker/webswing/
    container_name: simple_stock_zap
    image: ghcr.io/zaproxy/zaproxy:stable
    user: zap
    command: zap-webswing.sh
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      - simple_stock_net
    volumes:
      - ./zap/:/home/zap/
    depends_on:
      - app

volumes:
  db_data:
networks:
  simple_stock_net:
